### ISSUE TITLE
Updating lockfile should fail if package(s) can't be installed

### ISSUE THREAD

**Issue by asheplyakov** [stb-tester/apt2ostree#11]
```python
image = apt.build_image("Packages.lock",
    ['distcc', 'gcc-mipsel-linux-gnu'],
    ubuntu_apt_sources('bionic', 'arm64'))
```
Note: ``gcc-mipsel-linux-gnu`` is not available for arm64 architecture.

Expected result: ninja fails to generate/update ``Packages.lockfile`` with a nice error message (like "conflicting packages", or "package is not available", etc)

Actual result: ``Packages.lockfile`` gets created/updated without any errors. There's a warning:
```
W: Package gcc-mipsel-linux-gnu is not known, can't be installed
```
Yet it's sort of difficult to notice it since the log is a bit chatty.

**Comment by wmanley** [comment]
Yes, this would definitely be useful.  It would have to be fixed in aptly.  We could check that all the packages that were requested when sent to the dependency solver are present in the output of the dependency solver and fail if not.

**Comment by wmanley** [comment]
I've implemented this in aptly here: https://github.com/stb-tester/aptly/commit/2c78d7ee375c59e6a3a628504fb3751552846e75 .  Thanks for the suggestion.
