### ISSUE TITLE
Maintenance State

### ISSUE THREAD

**Issue by Malix-Labs** [stb-tester/apt2ostree#15]
Hello !

Is this project still maintained ?

If not, do you know any alternative?
Maybe it would be good to archive it too

**Comment by wmanley** [comment]
Sorry for the slow response: I was on holiday

Yes - this is maintained as much as it ever has been. It's an important part of our internal build systems (@stb-tester). We use this daily.

**Comment by wmanley** [comment]
Also note: https://github.com/stb-tester/apt2ostree/issues/14#issuecomment-1152449692

> We're happy if you use this project, but we mostly maintain it to be used with our internal build system - so we don't have much infrastructure to support other users - like a release process, backwards compatibility, documentation, etc. We released it as a demonstration of certain ideas that we wanted to spread. That said - it does work well for us, and there's little churn in practice.
